import type { BotBoard } from './types';

/**
 * Companion-radio environments built by meshcore-bot-firmware's release.yml.
 * Generated from MeshCore's platformio.ini variants — see scripts/generate-bot-boards.mjs.
 * Bump this list when the upstream MeshCore submodule pins a new variant set.
 */
export const BOT_BOARDS: readonly BotBoard[] = [
  { env: 'Ebyte_EoRa-S3_companion_radio_ble', platform: 'ESP32', board: 'ebyte_eora-s3', variant: 'ble' },
  { env: 'Ebyte_EoRa-S3_companion_radio_usb', platform: 'ESP32', board: 'ebyte_eora-s3', variant: 'usb' },
  { env: 'GAT562_30S_Mesh_Kit_companion_radio_ble', platform: 'NRF52', board: 'rak4631', variant: 'ble' },
  { env: 'GAT562_30S_Mesh_Kit_companion_radio_usb', platform: 'NRF52', board: 'rak4631', variant: 'usb' },
  { env: 'GAT562_Mesh_Tracker_Pro_companion_radio_ble', platform: 'NRF52', board: 'rak4631', variant: 'ble' },
  { env: 'GAT562_Mesh_Tracker_Pro_companion_radio_usb', platform: 'NRF52', board: 'rak4631', variant: 'usb' },
  { env: 'GAT562_Mesh_Watch13_companion_radio_ble', platform: 'NRF52', board: 'rak4631', variant: 'ble' },
  { env: 'Heltec_E213_companion_radio_ble', platform: 'ESP32', board: 'heltec_e213', variant: 'ble' },
  { env: 'Heltec_E213_companion_radio_usb', platform: 'ESP32', board: 'heltec_e213', variant: 'usb' },
  { env: 'Heltec_WSL3_companion_radio_ble', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'ble' },
  { env: 'Heltec_WSL3_companion_radio_usb', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'usb' },
  { env: 'Heltec_Wireless_Paper_companion_radio_ble', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'ble' },
  { env: 'Heltec_Wireless_Paper_companion_radio_usb', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'usb' },
  { env: 'Heltec_Wireless_Tracker_companion_radio_ble', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'ble' },
  { env: 'Heltec_Wireless_Tracker_companion_radio_usb', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'usb' },
  { env: 'Heltec_ct62_companion_radio_ble', platform: 'ESP32', board: 'esp32-c3-devkitm-1', variant: 'ble' },
  { env: 'Heltec_ct62_companion_radio_usb', platform: 'ESP32', board: 'esp32-c3-devkitm-1', variant: 'usb' },
  { env: 'Heltec_mesh_solar_companion_radio_ble', platform: 'NRF52', board: 'heltec_mesh_solar', variant: 'ble' },
  { env: 'Heltec_mesh_solar_companion_radio_usb', platform: 'NRF52', board: 'heltec_mesh_solar', variant: 'usb' },
  { env: 'Heltec_t096_companion_radio_ble', platform: 'NRF52', board: 'heltec_t096', variant: 'ble' },
  { env: 'Heltec_t096_companion_radio_usb', platform: 'NRF52', board: 'heltec_t096', variant: 'usb' },
  { env: 'Heltec_t114_companion_radio_ble', platform: 'NRF52', board: 'heltec_t114', variant: 'ble' },
  { env: 'Heltec_t114_companion_radio_usb', platform: 'NRF52', board: 'heltec_t114', variant: 'usb' },
  { env: 'Heltec_t114_without_display_companion_radio_ble', platform: 'NRF52', board: 'heltec_t114', variant: 'ble' },
  { env: 'Heltec_t114_without_display_companion_radio_usb', platform: 'NRF52', board: 'heltec_t114', variant: 'usb' },
  { env: 'Heltec_v2_companion_radio_ble', platform: 'ESP32', board: 'heltec_wifi_lora_32_V2', variant: 'ble' },
  { env: 'Heltec_v2_companion_radio_usb', platform: 'ESP32', board: 'heltec_wifi_lora_32_V2', variant: 'usb' },
  { env: 'Heltec_v3_companion_radio_ble', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'ble' },
  { env: 'Heltec_v3_companion_radio_usb', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'usb' },
  { env: 'KeepteenLT1_companion_radio_ble', platform: 'NRF52', board: 'keepteen_lt1', variant: 'ble' },
  { env: 'KeepteenLT1_companion_radio_usb', platform: 'NRF52', board: 'keepteen_lt1', variant: 'usb' },
  { env: 'LilyGo_T-Echo-Lite_companion_radio_ble', platform: 'NRF52', board: 't-echo', variant: 'ble' },
  { env: 'LilyGo_T-Echo_companion_radio_ble', platform: 'NRF52', board: 't-echo', variant: 'ble' },
  { env: 'LilyGo_T-Echo_companion_radio_usb', platform: 'NRF52', board: 't-echo', variant: 'usb' },
  { env: 'LilyGo_T3S3_sx1262_companion_radio_ble', platform: 'ESP32', board: 't3_s3_v1_x', variant: 'ble' },
  { env: 'LilyGo_T3S3_sx1262_companion_radio_usb', platform: 'ESP32', board: 't3_s3_v1_x', variant: 'usb' },
  { env: 'LilyGo_T3S3_sx1276_companion_radio_ble', platform: 'ESP32', board: 't3_s3_v1_x', variant: 'ble' },
  { env: 'LilyGo_T3S3_sx1276_companion_radio_usb', platform: 'ESP32', board: 't3_s3_v1_x', variant: 'usb' },
  { env: 'LilyGo_TBeam_1W_companion_radio_ble', platform: 'ESP32', board: 't_beam_1w', variant: 'ble' },
  { env: 'LilyGo_TBeam_1W_companion_radio_usb', platform: 'ESP32', board: 't_beam_1w', variant: 'usb' },
  { env: 'LilyGo_TDeck_companion_radio_ble', platform: 'ESP32', board: 't-deck', variant: 'ble' },
  { env: 'LilyGo_TDeck_companion_radio_usb', platform: 'ESP32', board: 't-deck', variant: 'usb' },
  { env: 'LilyGo_TETH_Elite_sx1262_companion_radio_ble', platform: 'ESP32', board: 'esp32s3box', variant: 'ble' },
  { env: 'LilyGo_TETH_Elite_sx1262_companion_radio_usb', platform: 'ESP32', board: 'esp32s3box', variant: 'usb' },
  { env: 'LilyGo_TLora_V2_1_1_6_companion_radio_ble', platform: 'ESP32', board: 'ttgo-lora32-v1', variant: 'ble' },
  { env: 'LilyGo_TLora_V2_1_1_6_companion_radio_usb', platform: 'ESP32', board: 'ttgo-lora32-v1', variant: 'usb' },
  { env: 'M5Stack_Unit_C6L_companion_radio_ble', platform: 'ESP32', board: 'esp32-c6-devkitm-1', variant: 'ble' },
  { env: 'M5Stack_Unit_C6L_companion_radio_usb', platform: 'ESP32', board: 'esp32-c6-devkitm-1', variant: 'usb' },
  { env: 'Mesh_pocket_companion_radio_ble', platform: 'NRF52', board: 'heltec_mesh_pocket', variant: 'ble' },
  { env: 'Mesh_pocket_companion_radio_usb', platform: 'NRF52', board: 'heltec_mesh_pocket', variant: 'usb' },
  { env: 'Meshadventurer_sx1262_companion_radio_ble', platform: 'ESP32', board: 'esp32doit-devkit-v1', variant: 'ble' },
  { env: 'Meshadventurer_sx1262_companion_radio_usb', platform: 'ESP32', board: 'esp32doit-devkit-v1', variant: 'usb' },
  { env: 'Meshadventurer_sx1268_companion_radio_ble', platform: 'ESP32', board: 'esp32doit-devkit-v1', variant: 'ble' },
  { env: 'Meshadventurer_sx1268_companion_radio_usb', platform: 'ESP32', board: 'esp32doit-devkit-v1', variant: 'usb' },
  { env: 'Meshtiny_companion_radio_ble', platform: 'NRF52', board: 'meshtiny', variant: 'ble' },
  { env: 'Meshtiny_companion_radio_usb', platform: 'NRF52', board: 'meshtiny', variant: 'usb' },
  { env: 'Minewsemi_me25ls01_companion_radio_ble', platform: 'NRF52', board: 'minewsemi_me25ls01', variant: 'ble' },
  { env: 'Minewsemi_me25ls01_companion_radio_usb', platform: 'NRF52', board: 'minewsemi_me25ls01', variant: 'usb' },
  { env: 'Nano_G2_Ultra_companion_radio_ble', platform: 'NRF52', board: 'nano-g2-ultra', variant: 'ble' },
  { env: 'Nano_G2_Ultra_companion_radio_usb', platform: 'NRF52', board: 'nano-g2-ultra', variant: 'usb' },
  { env: 'PicoW_companion_radio_usb', platform: 'RP2040', board: 'rpipicow', variant: 'usb' },
  { env: 'ProMicro_companion_radio_ble', platform: 'NRF52', board: 'promicro_nrf52840', variant: 'ble' },
  { env: 'ProMicro_companion_radio_usb', platform: 'NRF52', board: 'promicro_nrf52840', variant: 'usb' },
  { env: 'R1Neo_companion_radio_ble', platform: 'NRF52', board: 'rak4631', variant: 'ble' },
  { env: 'R1Neo_companion_radio_usb', platform: 'NRF52', board: 'rak4631', variant: 'usb' },
  { env: 'RAK_11310_companion_radio_usb', platform: 'RP2040', board: 'rakwireless_rak11300', variant: 'usb' },
  { env: 'RAK_3112_companion_radio_ble', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'ble' },
  { env: 'RAK_3112_companion_radio_usb', platform: 'ESP32', board: 'esp32-s3-devkitc-1', variant: 'usb' },
  { env: 'RAK_3401_companion_radio_ble', platform: 'NRF52', board: 'rak3401', variant: 'ble' },
  { env: 'RAK_3401_companion_radio_usb', platform: 'NRF52', board: 'rak3401', variant: 'usb' },
  { env: 'RAK_3x72_companion_radio_usb', platform: 'STM32', board: 'rak3172', variant: 'usb' },
  { env: 'RAK_4631_companion_radio_ble', platform: 'NRF52', board: 'rak4631', variant: 'ble' },
  { env: 'RAK_4631_companion_radio_usb', platform: 'NRF52', board: 'rak4631', variant: 'usb' },
  { env: 'RAK_WisMesh_Tag_companion_radio_ble', platform: 'NRF52', board: 'rak4631', variant: 'ble' },
  { env: 'RAK_WisMesh_Tag_companion_radio_usb', platform: 'NRF52', board: 'rak4631', variant: 'usb' },
  { env: 'SenseCap_Solar_companion_radio_ble', platform: 'NRF52', board: 'seeed_sensecap_solar', variant: 'ble' },
  { env: 'SenseCap_Solar_companion_radio_usb', platform: 'NRF52', board: 'seeed_sensecap_solar', variant: 'usb' },
  { env: 'Station_G2_companion_radio_ble', platform: 'ESP32', board: 'station-g2', variant: 'ble' },
  { env: 'Station_G2_companion_radio_usb', platform: 'ESP32', board: 'station-g2', variant: 'usb' },
  { env: 'T_Beam_S3_Supreme_SX1262_companion_radio_ble', platform: 'ESP32', board: 't_beams3_supreme', variant: 'ble' },
  { env: 'Tbeam_SX1262_companion_radio_ble', platform: 'ESP32', board: 'ttgo-t-beam', variant: 'ble' },
  { env: 'Tbeam_SX1276_companion_radio_ble', platform: 'ESP32', board: 'ttgo-t-beam', variant: 'ble' },
  { env: 'ThinkNode_M1_companion_radio_ble', platform: 'NRF52', board: 'thinknode_m1', variant: 'ble' },
  { env: 'ThinkNode_M1_companion_radio_usb', platform: 'NRF52', board: 'thinknode_m1', variant: 'usb' },
  { env: 'ThinkNode_M2_companion_radio_ble', platform: 'ESP32', board: 'ESP32-S3-WROOM-1-N4', variant: 'ble' },
  { env: 'ThinkNode_M2_companion_radio_usb', platform: 'ESP32', board: 'ESP32-S3-WROOM-1-N4', variant: 'usb' },
  { env: 'ThinkNode_M3_companion_radio_ble', platform: 'NRF52', board: 'thinknode_m3', variant: 'ble' },
  { env: 'ThinkNode_M3_companion_radio_usb', platform: 'NRF52', board: 'thinknode_m3', variant: 'usb' },
  { env: 'ThinkNode_M5_companion_radio_ble', platform: 'ESP32', board: 'ESP32-S3-WROOM-1-N4', variant: 'ble' },
  { env: 'ThinkNode_M5_companion_radio_usb', platform: 'ESP32', board: 'ESP32-S3-WROOM-1-N4', variant: 'usb' },
  { env: 'ThinkNode_M6_companion_radio_ble', platform: 'NRF52', board: 'thinknode_m6', variant: 'ble' },
  { env: 'ThinkNode_M6_companion_radio_usb', platform: 'NRF52', board: 'thinknode_m6', variant: 'usb' },
  { env: 'Tiny_Relay_companion_radio_usb', platform: 'STM32', board: 'tiny_relay', variant: 'usb' },
  { env: 'WioTrackerL1Eink_companion_radio_ble', platform: 'NRF52', board: 'seeed-wio-tracker-l1', variant: 'ble' },
  { env: 'WioTrackerL1_companion_radio_ble', platform: 'NRF52', board: 'seeed-wio-tracker-l1', variant: 'ble' },
  { env: 'WioTrackerL1_companion_radio_usb', platform: 'NRF52', board: 'seeed-wio-tracker-l1', variant: 'usb' },
  { env: 'Xiao_C3_companion_radio_ble', platform: 'ESP32', board: 'seeed_xiao_esp32c3', variant: 'ble' },
  { env: 'Xiao_C3_companion_radio_usb', platform: 'ESP32', board: 'seeed_xiao_esp32c3', variant: 'usb' },
  { env: 'Xiao_S3_WIO_companion_radio_ble', platform: 'ESP32', board: 'seeed_xiao_esp32s3', variant: 'ble' },
  { env: 'Xiao_S3_WIO_companion_radio_usb', platform: 'ESP32', board: 'seeed_xiao_esp32s3', variant: 'usb' },
  { env: 'Xiao_nrf52_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'Xiao_nrf52_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'Xiao_rp2040_companion_radio_usb', platform: 'RP2040', board: 'seeed_xiao_rp2040', variant: 'usb' },
  { env: 'heltec_tracker_v2_companion_radio_ble', platform: 'ESP32', board: 'heltec_tracker_v2', variant: 'ble' },
  { env: 'heltec_tracker_v2_companion_radio_usb', platform: 'ESP32', board: 'heltec_tracker_v2', variant: 'usb' },
  { env: 'heltec_v4_companion_radio_ble', platform: 'ESP32', board: 'heltec_v4', variant: 'ble' },
  { env: 'heltec_v4_companion_radio_usb', platform: 'ESP32', board: 'heltec_v4', variant: 'usb' },
  { env: 'heltec_v4_tft_companion_radio_ble', platform: 'ESP32', board: 'heltec_v4', variant: 'ble' },
  { env: 'heltec_v4_tft_companion_radio_usb', platform: 'ESP32', board: 'heltec_v4', variant: 'usb' },
  { env: 'ikoka_handheld_nrf_e22_30dbm_096_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_handheld_nrf_e22_30dbm_096_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_handheld_nrf_e22_30dbm_096_rotated_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_handheld_nrf_e22_30dbm_096_rotated_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_nano_nrf_22dbm_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_nano_nrf_22dbm_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_nano_nrf_30dbm_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_nano_nrf_30dbm_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_nano_nrf_33dbm_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_nano_nrf_33dbm_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_stick_nrf_22dbm_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_stick_nrf_22dbm_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_stick_nrf_30dbm_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_stick_nrf_30dbm_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'ikoka_stick_nrf_33dbm_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
  { env: 'ikoka_stick_nrf_33dbm_companion_radio_usb', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'usb' },
  { env: 'nibble_screen_connect_companion_radio_ble', platform: 'ESP32', board: 'esp32-s3-zero', variant: 'ble' },
  { env: 'nibble_screen_connect_companion_radio_usb', platform: 'ESP32', board: 'esp32-s3-zero', variant: 'usb' },
  { env: 't1000e_companion_radio_ble', platform: 'NRF52', board: 'tracker-t1000-e', variant: 'ble' },
  { env: 't1000e_companion_radio_usb', platform: 'NRF52', board: 'tracker-t1000-e', variant: 'usb' },
  { env: 'waveshare_rp2040_lora_companion_radio_usb', platform: 'RP2040', board: 'pico', variant: 'usb' },
  { env: 'wio-e5-mini_companion_radio_usb', platform: 'STM32', board: 'lora_e5_mini', variant: 'usb' },
  { env: 'wio-e5_companion_radio_usb', platform: 'STM32', board: 'lora_e5_dev_board', variant: 'usb' },
  { env: 'wio_wm1110_companion_radio_ble', platform: 'NRF52', board: 'seeed-xiao-afruitnrf52-nrf52840', variant: 'ble' },
];

const BOARD_BY_ENV = new Map(BOT_BOARDS.map((b) => [b.env, b]));
export function getBoardByEnv(env: string): BotBoard | undefined {
  return BOARD_BY_ENV.get(env);
}
